### ISSUE TITLE
Our current release process is broken it keeps a draft PR and a tagged empty release

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-project-template#351]
### Issue description

<img width="931" alt="CleanShot 2023-03-23 at 10 46 01@2x" src="https://user-images.githubusercontent.com/864788/227164764-d999268d-7613-42cb-99b4-5b2e38b5a3f6.png">

This happens almost all the time.

**Comment by sdelamo** [comment]
@behnazh-w  @melix @alvarosanchez any ideas?

**Comment by melix** [comment]
I have no idea. I looked at our internal GH actions but the only recent change is on the release notes action which we don't use anymore...

**Comment by behnazh-w** [comment]
That's strange. I'll revert the change in [this PR](https://github.com/micronaut-projects/micronaut-project-template/pull/346) if it has caused this behavior.

**Comment by alvarosanchez** [comment]
Usually when a GitHub release is moved back to draft is because it has been edited. Our custom GitHub actions have always taken care of this by re-closing the releases, but perhaps something that was there and now is missing is preventing this to work.

I have created https://github.com/micronaut-projects/github-actions/pull/23, hope it helps.

**Comment by sdelamo** [comment]
The issue is still happening.  I just had this problem with Micronaut Liquibase.
